In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [84]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import random

#np.random.seed(10)
filenames = []
for i in range(6):
    # Create a figure and axis
    fig, ax = plt.subplots()

    # Creating a square with unit side (1x1)
    square = patches.Rectangle((-0.5, -0.5), 1, 1, edgecolor='blue', facecolor="none")
    ax.add_patch(square)

    # Creating a circle with unit radius
    circle = plt.Circle((3, 0), radius=1, edgecolor='red', facecolor="none")
    ax.add_patch(circle)

    # Setting the limits of the plot
    ax.set_xlim(-2, 5)
    ax.set_ylim(-2, 2)

    # Equal aspect ratio to ensure the square and circle are shown correctly
    ax.set_aspect('equal', adjustable='box')
    plt.axhline(y=0, color='green', linestyle='dotted')
    plt.axvline(x=0, color='green', linestyle='dotted')
    plt.axvline(x=3, color='green', linestyle='dotted')
    #plt.axvline(x=2.5, color='green', linestyle='dotted')

    # Adding arrows
    plt.annotate('', xy=(-0.5, -0.7), xytext=(0.5, -0.7), arrowprops=dict(arrowstyle='<->', color='black'))
    plt.text(0, -1, '1 unit', ha='center')

    plt.annotate('', xy=(3,0), xytext=( np.cos(np.pi/4)+3,  np.sin(np.pi/4)), arrowprops=dict(arrowstyle='<-', color='black'))
    plt.text(3.5, 0.1, '1 unit', ha='center')


    x, y = np.random.uniform(-2, 5, 100), np.random.uniform(-2, 2, 100)
    z=((x-3)**2)+(y**2)
    
    A = np.column_stack((x, y, z))
    mask = A[:, 2] <= 1
    A = A[mask]
    
    square_condition = (x >= -0.5) & (x <= 0.5) & (y >= -0.5) & (y <= 0.5)
    inside_square = np.sum(square_condition)
    inside_circle = np.sum(z <= 1)
    plt.scatter(x, y,s=5)
    plt.title(f'Step {i}/5')
    
    # Save frame
    filename = f'frames/step_{i}.png'
    filenames.append(filename)
    plt.savefig(filename)
    plt.close()
    
    
   


In [87]:
A = np.column_stack((x, y, z))
mask = A[:, 2] <= 1
A = A[mask]
A

array([[ 2.92872466,  0.05733907,  0.00836794],
       [ 2.31644826,  0.59329861,  0.81924622],
       [ 3.18991003,  0.72078428,  0.55559579],
       [ 2.68301043,  0.90667593,  0.92254364],
       [ 3.30266353,  0.72515332,  0.61745255],
       [ 2.07973221,  0.07840696,  0.85304045],
       [ 2.77390586, -0.26852793,  0.12322581]])

In [85]:
np.column_stack((x, y, z))

array([[ 2.92872466e+00,  5.73390672e-02,  8.36794252e-03],
       [ 2.07176062e+00,  1.24116481e+00,  2.40211844e+00],
       [ 1.72681410e+00, -1.92051743e+00,  5.30938955e+00],
       [ 1.57296537e+00, -6.07075251e-01,  2.40496820e+00],
       [-8.91560970e-01,  9.62693911e-01,  1.60710264e+01],
       [ 4.84126061e+00, -1.09821722e-01,  3.40230145e+00],
       [-5.12678608e-01, -6.78062523e-01,  1.27986798e+01],
       [ 1.47193751e+00, -6.35997676e-01,  2.73946802e+00],
       [ 2.69882135e-01, -1.41434489e+00,  9.45391501e+00],
       [ 2.31644826e+00,  5.93298612e-01,  8.19246219e-01],
       [ 1.04137132e+00,  1.52968321e+00,  6.17615701e+00],
       [ 1.24619891e-01, -2.68088566e-01,  8.33968225e+00],
       [ 4.29231736e+00, -6.09536202e-02,  1.67379950e+00],
       [ 8.10156787e-01,  8.41982333e-01,  5.50434755e+00],
       [ 4.21266233e-01,  9.56244376e-02,  6.65901187e+00],
       [ 6.47196870e-01,  3.62076731e-01,  5.66678213e+00],
       [ 2.23507032e+00, -1.17299328e+00

In [48]:
inside_circle

5

In [42]:
((x-3)**2)+(y**2)

array([ 0.70912837, 26.85751349,  4.25569491,  0.06076211,  3.84517181,
       11.94297172, 13.84462222,  0.79784053, 17.3561302 , 19.93528949])

In [31]:
x**2

array([8.42238295e+00, 1.30839885e-01, 2.00271950e+01, 1.62484446e+01,
       4.44539698e-02, 2.14735315e+01, 4.70722359e+00, 3.14341789e+01,
       3.55958362e+01, 4.41634221e-01, 3.19523569e+01, 2.65188333e+01,
       7.32395026e+00, 2.64225847e+00, 2.68872945e+01, 2.01173171e-01,
       2.24589574e+01, 1.43319541e+01, 3.34378771e+00, 3.02213255e+00,
       1.94755714e+01, 1.28327777e+01, 3.46650553e+01, 4.21299393e+00,
       2.05244163e-01, 1.67932358e+00, 3.84177481e+00, 2.59481934e+00,
       2.16684879e+00, 2.78538319e+00, 6.23816585e+00, 7.31524075e+00,
       1.46108053e+01, 1.39515040e+00, 2.53498845e+01, 1.17681687e+00,
       3.33861013e+01, 3.38934711e+00, 8.81509522e-01, 3.43816390e+01,
       6.34584968e+00, 7.75519095e+00, 3.68614637e+00, 1.71263758e+00,
       3.40031715e+00, 2.81310218e+01, 1.75396090e+00, 3.85514211e+00,
       6.86308907e+00, 5.82788056e-04, 1.46864806e-05, 5.11357229e+00,
       1.49605211e+01, 3.23792789e+01, 2.62208506e-02, 1.17283528e+00,
      

In [64]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

# Step 1: Create a Matplotlib graph with red dots
#np.random.seed(0)  # For reproducibility
x = np.random.rand(10) * 10  # Random x coordinates
y = np.random.rand(10) * 10  # Random y coordinates

plt.figure(figsize=(6, 4))
plt.scatter(x, y, color='red')  # Scatter plot with red dots
#plt.grid(True)

# Step 2: Save the graph as an image
image_path = 'C:/Users/milar/Desktop/My_Asus_folder/Codes/Docusaurus_site_git/my-website/docs/jnb/red_dots_plot.png'
plt.savefig(image_path, dpi=300)
plt.close()

# Step 3: Process the image with OpenCV to count the red dots

# Read the saved image
image = cv2.imread(image_path)

# Convert the image to the RGB color space (OpenCV uses BGR by default)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Define the range for red color in RGB
lower_red = np.array([100, 0, 0])
upper_red = np.array([255, 100, 100])

# Create a mask that isolates the red dots
mask = cv2.inRange(image_rgb, lower_red, upper_red)

# Find contours in the mask
contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Count the number of red dots
num_red_dots = len(contours)

num_red_dots

11

In [69]:
import random

def estimate_pi(num_samples):
    inside_circle = 0

    for _ in range(num_samples):
        x, y = random.random(), random.random()
        if x**2 + y**2 <= 1:
            inside_circle += 1

    return (inside_circle / num_samples) * 4

# Example usage
num_samples = 1000000  # The more samples, the more accurate the estimate
pi_estimate = estimate_pi(num_samples)
print(f"Estimated value of Pi: {pi_estimate}")


Estimated value of Pi: 3.14146
