In [1]:
import numpy as np
from scipy.stats import norm
from scipy.optimize import minimize

# Generate some example data with a known mean and standard deviation
np.random.seed(42)
true_mean = 3.0
true_std = 2.0
data = np.random.normal(true_mean, true_std, 100)

# Define the likelihood function for a normal distribution
def neg_log_likelihood(params, data):
    mean, std = params
    log_likelihood = np.sum(norm.logpdf(data, loc=mean, scale=std))
    return -log_likelihood

# Initial guess for the parameters
initial_guess = [0, 1]

# Use the minimize function from SciPy to find the MLE estimates
result = minimize(neg_log_likelihood, initial_guess, args=(data,))
mle_mean, mle_std = result.x

# Print the results
print("True Mean:", true_mean)
print("True Standard Deviation:", true_std)
print("MLE Estimated Mean:", mle_mean)
print("MLE Estimated Standard Deviation:", mle_std)


True Mean: 3.0
True Standard Deviation: 2.0
MLE Estimated Mean: 15659.328975691993
MLE Estimated Standard Deviation: -3568.993719666323


In [41]:
import numpy as np
from scipy.optimize import minimize

# Generate some example data
np.random.seed(2609)
data = np.random.normal(loc=155, scale=7, size=100000)

# Define the likelihood function for a normal distribution
def likelihood(params, data):
    mean, std_dev = params
    likelihood_values = np.log(np.sqrt(2*np.pi*(std_dev**2))) + (0.5*(((data - mean) / std_dev)**2))
    return np.sum(likelihood_values)

# Initial guess for the parameters
initial_params = [0, 1]

# Use scipy's minimize function to maximize the likelihood
result = minimize(likelihood, initial_params, args=(data,))
estimated_mean, estimated_std_dev = result.x

# Print the results
print("Estimated Mean:", estimated_mean)
print("Estimated Standard Deviation:", estimated_std_dev)
print("Convergence Status:", result.success)
print("Optimal Value of the Objective Function:", result.fun)



Estimated Mean: 154.99808505357024
Estimated Standard Deviation: 6.996996924429178
Convergence Status: True
Optimal Value of the Objective Function: 336441.9597128625


In [21]:
-0.5 * ((data - 15) / std_dev)**2

array([-210.05764554, -197.24427249, -213.16352098, -231.6204071 ,
       -195.34434641, -195.34467092, -232.83121287, -215.64317261,
       -190.72071538, -210.99838657, -190.83902412, -190.79385703,
       -204.8685183 , -163.56471575, -166.98931411, -188.91233305,
       -180.25629103, -206.33432234, -182.25177235, -172.75122685,
       -230.38703854, -195.50996146, -201.35284412, -172.51998997,
       -189.26052178, -202.2246037 , -177.64252156, -207.58453487,
       -188.16760962, -194.20866763, -188.14689318, -238.76103093,
       -199.73014659, -179.40515763, -216.78918831, -176.32835661,
       -204.1990839 , -162.72675102, -174.31831811, -203.95660189,
       -215.04199804, -203.44204917, -197.69372161, -194.02325781,
       -171.52257383, -185.86220367, -190.89331862, -221.70119822,
       -206.93140256, -166.29335219, -206.5341946 , -192.37249857,
       -186.69067169, -212.42059972, -221.15147046, -219.05924371,
       -183.56779256, -193.86355863, -206.68013636, -219.98674

In [22]:
-(0.5*(((data - 15) / std_dev)**2))

array([-210.05764554, -197.24427249, -213.16352098, -231.6204071 ,
       -195.34434641, -195.34467092, -232.83121287, -215.64317261,
       -190.72071538, -210.99838657, -190.83902412, -190.79385703,
       -204.8685183 , -163.56471575, -166.98931411, -188.91233305,
       -180.25629103, -206.33432234, -182.25177235, -172.75122685,
       -230.38703854, -195.50996146, -201.35284412, -172.51998997,
       -189.26052178, -202.2246037 , -177.64252156, -207.58453487,
       -188.16760962, -194.20866763, -188.14689318, -238.76103093,
       -199.73014659, -179.40515763, -216.78918831, -176.32835661,
       -204.1990839 , -162.72675102, -174.31831811, -203.95660189,
       -215.04199804, -203.44204917, -197.69372161, -194.02325781,
       -171.52257383, -185.86220367, -190.89331862, -221.70119822,
       -206.93140256, -166.29335219, -206.5341946 , -192.37249857,
       -186.69067169, -212.42059972, -221.15147046, -219.05924371,
       -183.56779256, -193.86355863, -206.68013636, -219.98674

In [13]:
0.5 * ((data - 15) / std_dev)**2

array([210.05764554, 197.24427249, 213.16352098, 231.6204071 ,
       195.34434641, 195.34467092, 232.83121287, 215.64317261,
       190.72071538, 210.99838657, 190.83902412, 190.79385703,
       204.8685183 , 163.56471575, 166.98931411, 188.91233305,
       180.25629103, 206.33432234, 182.25177235, 172.75122685,
       230.38703854, 195.50996146, 201.35284412, 172.51998997,
       189.26052178, 202.2246037 , 177.64252156, 207.58453487,
       188.16760962, 194.20866763, 188.14689318, 238.76103093,
       199.73014659, 179.40515763, 216.78918831, 176.32835661,
       204.1990839 , 162.72675102, 174.31831811, 203.95660189,
       215.04199804, 203.44204917, 197.69372161, 194.02325781,
       171.52257383, 185.86220367, 190.89331862, 221.70119822,
       206.93140256, 166.29335219, 206.5341946 , 192.37249857,
       186.69067169, 212.42059972, 221.15147046, 219.05924371,
       183.56779256, 193.86355863, 206.68013636, 219.98674669,
       190.53131922, 196.30405509, 178.48528906, 176.79

In [10]:
np.log(std_dev*(np.sqrt(2*np.pi)))

2.8648486822599857

In [11]:
0.5 * np.log(2 * np.pi * std_dev**2)

2.864848682259986

In [9]:
std_dev=7

In [8]:
data-2

array([ 3.99342831e+00,  2.72347140e+00,  4.29537708e+00,  6.04605971e+00,
        2.53169325e+00,  2.53172609e+00,  6.15842563e+00,  4.53486946e+00,
        2.06105123e+00,  4.08512009e+00,  2.07316461e+00,  2.06854049e+00,
        3.48392454e+00, -8.26560489e-01, -4.49835665e-01,  1.87542494e+00,
        9.74337759e-01,  3.62849467e+00,  1.18395185e+00,  1.75392597e-01,
        5.93129754e+00,  2.54844740e+00,  3.13505641e+00,  1.50503628e-01,
        1.91123455e+00,  3.22184518e+00,  6.98012845e-01,  3.75139604e+00,
        1.79872262e+00,  2.41661250e+00,  1.79658678e+00,  6.70455637e+00,
        2.97300555e+00,  8.84578142e-01,  4.64508982e+00,  5.58312700e-01,
        3.41772719e+00, -9.19340248e-01,  3.43627902e-01,  3.39372247e+00,
        4.47693316e+00,  3.34273656e+00,  2.76870344e+00,  2.39779261e+00,
        4.29560193e-02,  1.56031158e+00,  2.07872246e+00,  5.11424445e+00,
        3.68723658e+00, -5.26080311e-01,  3.64816794e+00,  2.22983544e+00,
        1.64615600e+00,  

In [5]:
a

34

In [6]:
b

45